### ISSUE TITLE
Data source freshness check failing due to issue with timestamp casting

### ISSUE THREAD

**Issue by ssheftel** [Teradata/dbt-teradata#22]
### Data source freshness checks are failing due to issue with timestamp casting
When the data source freshness checks are set i.e. `warn_after` as described in the [dbt fundamentals course](https://courses.getdbt.com/courses/take/fundamentals/lessons/27962331-source-freshness) running the `dbt source freshness` command produces timestamp type conversion error of  
```
Expected a timestamp value when querying field '_loaded_at' of table "jaffle_shop"."raw_orders" but received value of type 'date' instead
``` 
instead of a warning as would be expected

### Steps To Reproduce
The following steps assume the current date is 2022-01-26 and the database is seeded with the [jaffle_shop](https://github.com/Teradata/jaffle_shop-dev) sample data.

1. Add the `_loaded_at` column to the `jaffle_shop.raw_orders` table:  
```sql
ALTER TABLE jaffle_shop.raw_orders ADD _loaded_at TIMESTAMP;
```
2. Set the `_loaded_at` column value: 
```sql
UPDATE jaffle_shop.raw_orders SET _loaded_at=CAST(CAST('2022-01-24' AS DATE) AS TIMESTAMP(0));
```
3. Add a source configuration yml file (models/staging/src_jaffle_shop.yml) and set the `warn_after` value

```yml
---
# file: models/staging/src_jaffle_shop.yml
version: 2

sources:
  - name: jaffle_shop
    database: jaffle_shop
    schema: jaffle_shop
    tables:
      - name: raw_customers
      - name: raw_payments
      - name: raw_orders
        loaded_at_field: _loaded_at
        freshness:
          warn_after: {count: 24, period: hour}
```

4. Run `dbt source freshness` to trigger the freshness warning

### Expected behavior
The expected behavior is for the Freshness warning to be logged.

### Screenshots and log output
Instead of the warning the following error occurs: 

```text
Database Error in source raw_orders (models/staging/src_jaffle_shop.yml)

Expected a timestamp value when querying field '_loaded_at' of table "jaffle_shop"."raw_orders" but received value of type 'str' instead
```

Screenshot
<img width="1500" alt="Screen Shot 2022-01-26 at 4 15 25 PM" src="https://user-images.githubusercontent.com/2941263/151248140-b423a232-2605-4ca7-9090-5508651eae1c.png">

It appears as if the issue is related to the casting in the generated query for checking the freshness. The generated querie is 
```sql
select
      max(_loaded_at) as max_loaded_at,
      CAST ( CAST (CURRENT_TIMESTAMP AS FORMAT 'YYYY-MM-DD HH:MI:SS.S(F)Z') AS VARCHAR(32)) as snapshotted_at
    from "jaffle_shop"."raw_orders"
```

Which is casting the `snapshotted_at` field to a string rather than a timestamp as dbt expects.

**The output of `dbt --version`:** 
```text
installed version: 1.0.0
   latest version: unknown

The latest version of dbt could not be determined!
Make sure that the following URL is accessible:
https://pypi.org/pypi/dbt/json

Plugins:
  - teradata: 1.0.0.0
```

**The operating system you're using:** MacOS Big Sur (11.6.2)

**The output of `python --version`:** `Python 3.8.12`

### Additional context

I am new to dbt so please forgive me in advance if this is not a dbt-teradata plugin issue or if I have not configured the `warn_after` freshness check correctly.
